// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {



  static FirebaseOptions get currentPlatform {



    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNE07ll70aNDsKpQI3LgHMOaFRxiOowjo',
    appId: '1:291418405084:android:da7b13824912a703961c19',
    messagingSenderId: '291418405084',
    projectId: 'orivo-232c5',
    storageBucket: 'orivo-232c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOyGGxXrao-eegH86bhDQCnE0c585I7G8',
    appId: '1:291418405084:ios:364ebdb8a75c2f8b961c19',
    messagingSenderId: '291418405084',
    projectId: 'orivo-232c5',
    storageBucket: 'orivo-232c5.firebasestorage.app',
    iosBundleId: 'com.logixhunt.auro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOyGGxXrao-eegH86bhDQCnE0c585I7G8',
    appId: '1:291418405084:ios:364ebdb8a75c2f8b961c19',
    messagingSenderId: '291418405084',
    projectId: 'orivo-232c5',
    storageBucket: 'orivo-232c5.firebasestorage.app',
    iosBundleId: 'com.logixhunt.auro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvZ9oakps-W6HmE9DGQ72d9bKRluVQKyM',
    appId: '1:291418405084:web:b731d0ab8a957820961c19',
    messagingSenderId: '291418405084',
    projectId: 'orivo-232c5',
    authDomain: 'orivo-232c5.firebaseapp.com',
    storageBucket: 'orivo-232c5.firebasestorage.app',
    measurementId: 'G-0B3X800L2H',
  );


}


